[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm run build"  # 또는 "yarn build", 너가 사용하는 빌드 명령어를 사용해
  publish = "build"  # 빌드된 파일이 저장되는 폴더 (React 앱의 기본 build 폴더)
  
[context.production.environment]
  NODE_ENV = "production"  # 프로덕션 환경 설정